### ISSUE TITLE
vtab data preprocess with input range (-1, 1)

### ISSUE THREAD

**Issue by KMnP** [google-research/head2toe#3]
Hi, 

Thanks for sharing the code. I wonder if there a reason why setting input range to (-1, 1) (https://github.com/google-research/head2toe/blob/main/head2toe/input_pipeline.py#L152) instead of (0, 1) in vtab(https://github.com/google-research/task_adaptation/blob/master/scripts/run_all_tasks.sh#L57)？

**Comment by evcu** [comment]
This is actually very nice catch. We wanted to be comparable to the Meta-dataset data-processing and thus used this scaling. This might explain few small differences we got with VTAB. I will take a note and try reruning (at-least some) of our results with 0-1 scaling.

https://github.com/google-research/meta-dataset/blob/main/meta_dataset/data/read_episodes.py#L245 

Thanks for reaching out.
