### ISSUE TITLE
Instructions to run experiments

### ISSUE THREAD

**Issue by arxyzan** [google-research/head2toe#4]
Hello Utku, Thanks for this great research. Just wanted to know if you could publish the instructions to run the codes and possibly training on custom datasets and models.
Best regards,
Aryan

**Comment by evcu** [comment]
Hi Aryan,

Thanks for your interest. I plan sharing checkpoints and instructions to reproduce by next week. ICML deadline is going busy.

**Comment by arxyzan** [comment]
Thanks, looking forward to that!
