### ISSUE TITLE
Feature Selection Method

### ISSUE THREAD

**Issue by ShivainVij** [google-research/head2toe#6]
Hi! This is some really cool work. 

I was hoping if you could clarify some parts of the research paper for me. 

How are you able to choose the target size? What I mean is, since the final avgpooling layer in ResNet50 has 2048 input features, does that mean that the maximum number of features you can select from each layer (after pooling to reduce dimensionality) is 2048?

**Comment by evcu** [comment]
Indeed, we don't do pooling over neurons/channels. It's over 1d/2d spatial dimensions. See below

https://github.com/google-research/head2toe/blob/f71a517cc16c36530c37ea023574ef7a34e1da19/head2toe/models/finetune.py#L583
