### ISSUE TITLE
Chosen Layers

### ISSUE THREAD

**Issue by ShivainVij** [google-research/head2toe#7]
I'm a little bit confused about which layers are being selected in the Resnet50 Head2Toe implementation. It says in the paper that you select features before and after the final pooling layer. Aren't the features from before the final pooling layer the same as the outputs of the final activation function in the previous Bottleneck block? Wouldn't this result in selecting the same features twice? 
![image](https://user-images.githubusercontent.com/26453836/159979416-0ba06c9d-c412-432c-b004-e4dfaab319ea.png)

**Comment by evcu** [comment]
Sorry for the delay responding and thanks for the question. So we take features after activation and before convolutions so it looks like this
```
x = normalization(x)
x = activation(x)
endpoints['conv3'] = x
x = conv(x)
x = shortcut + x
```

So the features before pooling are different than the last feature at the block, due to convolution and shortcut addition.
